# Copyright 2021 The OpenSSL Project Authors. All Rights Reserved.
#
# Licensed under the Apache License 2.0 (the "License").  You may not use
# this file except in compliance with the License.  You can obtain a copy
# in the file LICENSE in the source distribution or at
# https://www.openssl.org/source/license.html

name: CIFuzz
on: [pull_request, push]
permissions:
  contents: read

jobs:
  Fuzzing:
    runs-on: ubuntu-latest
    steps:
    - name: Clear unnecessary files
      run: |
        df
        sudo apt clean
        sudo rm -rf /usr/share/dotnet/ /usr/share/swift /usr/local/.ghcup/ /usr/local/share/powershell /usr/local/share/chromium /usr/local/lib/android /usr/local/lib/node_modules
        df
    - name: Build Fuzzers
      uses: bernd-edlinger/oss-fuzz/infra/cifuzz/actions/build_fuzzers@master
      with:
        oss-fuzz-project-name: 'openssl'
        dry-run: false
        sanitizer: coverage
    - name: Run Fuzzers
      uses: bernd-edlinger/oss-fuzz/infra/cifuzz/actions/run_fuzzers@master
      with:
        oss-fuzz-project-name: 'openssl'
        fuzz-seconds: 600
        dry-run: false
        sanitizer: coverage
