---
name: OS Zoo CI for 1.1.1

on: [push]

permissions:
  contents: read

jobs:
  # This has to be a separate job, it seems, because we want to use a
  # container for it.
  unix-container:
    strategy:
      fail-fast: false
      matrix:
        image: ['alpine:edge', 'alpine:latest']
        cc: ['gcc', 'clang']
    runs-on: ubuntu-latest
    container:
      image: ${{ matrix.image }}
    steps:
    - name: install packages
      run: |
        apk --no-cache add build-base perl linux-headers ${{ matrix.cc }}

    - uses: actions/checkout@v4

    - name: config
      run: |
        cc="${{ matrix.cc }}"

        extra_cflags=""
        if [[ ${cc} == "clang" ]] ; then
          # https://www.openwall.com/lists/musl/2022/02/16/14
          extra_cflags="-Wno-sign-compare"
        fi

        ls --full-time ./config
        find ./* -type f -exec touch {} \;
        ls --full-time ./config
        CC=${{ matrix.cc }} ./config no-shared \
            --strict-warnings -DOPENSSL_USE_IPV6=0 ${extra_cflags}

    - name: config dump
      run: ./configdata.pm --dump
    - name: make
      run: make -s -j4
    - name: make test
      run: make test
  unix:
    strategy:
      fail-fast: false
      matrix:
        os: [
          macos-11,
          macos-12,
          ubuntu-20.04,
        ]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - name: config
      run: |
        CC=${{ matrix.zoo.cc }} ./config \
            --strict-warnings
    - name: config dump
      run: ./configdata.pm --dump
    - name: make
      run: make -s -j4
    - name: make test
      run: make test
  windows:
    strategy:
      fail-fast: false
      matrix:
        os: [
          windows-2019,
          windows-2022
        ]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - uses: ilammy/msvc-dev-cmd@v1
    - uses: ilammy/setup-nasm@v1
    - uses: shogo82148/actions-setup-perl@v1
    - name: prepare the build directory
      run: mkdir _build
    - name: config
      working-directory: _build
      run: |
        perl ..\Configure VC-WIN64A
    - name: config dump
      working-directory: _build
      run: ./configdata.pm --dump
    - name: build
      working-directory: _build
      run: nmake /S
    - name: test
      working-directory: _build
      run: nmake test
